# This is a basic workflow to help you get started with Actions

name: Build OpiumNetStat Desktop App Installer

on:
  push:
    branches:
      - master

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true 
  DESKTOP_APP_NAME: SimpleFrameworkApp.sln    
  DESKTOP_APP_PACKAGE_PATH: 'OpiumNetStat\Opium.Installer\bin\Releases'   
  INSTALLER_PATH: 'artifacts'  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.1
        with:
         vs-version: "[16.4,16.9)"
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
    
      - name: Restore NuGet packages
        run: nuget restore ${{ env.DESKTOP_APP_NAME }}
      
      - name: Build
        run: msbuild ${{ env.DESKTOP_APP_NAME }} /p:Configuration=Release /p:Platform="x86"
       
      
            
