# This is a basic workflow to help you get started with Actions

name: Build OpiumNetStat Desktop App Installer

on:
  push:
    branches:
      - master

env:
  DESKTOP_APP_NAME: SimpleFrameworkApp.sln    
  DESKTOP_APP_PACKAGE_PATH: 'OpiumNetStat\Opium.Installer\bin\Releases'   
  INSTALLER_PATH: 'artifacts'  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: make_installer.cmd
       
      
            
